CREATE TABLE Persons (
  id         INTEGER      NOT NULL IDENTITY ,
  first_name VARCHAR(255) NOT NULL,
  last_name  VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE BlacklistedPersons (
  personal_id varchar(255) NOT NULL, 
  PRIMARY KEY (personal_id)
);

CREATE TABLE LoanApplications (
  id           INT NOT NULL IDENTITY,
  name         varchar(255) NOT NULL,
  surname      varchar(255) NOT NULL,
  personal_id  varchar(255) NOT NULL,
  amount       numeric(19, 0) NOT NULL,
  term         int NOT NULL,
  country_code varchar(255) NOT NULL,
  created      datetime NOT NULL,
  PRIMARY KEY (id));

CREATE TABLE LimitsCountryRequests (
  id             INT GENERATED BY DEFAULT AS IDENTITY,
  country_code   VARCHAR(255) NOT NULL,
  date_start     DATETIME NOT NULL,
  date_end       DATETIME NOT NULL,
  requests_limit INT NOT NULL,
  requested      INT DEFAULT 0 NOT NULL,
  PRIMARY KEY (id));

CREATE TABLE DecisionsOnLoanApplication (
  id                  int GENERATED BY DEFAULT AS IDENTITY,
  decision_date       datetime NOT NULL,
  approved            tinyint NOT NULL,
  fk_loan_application int NOT NULL UNIQUE,
  PRIMARY KEY (id));
ALTER TABLE DecisionsOnLoanApplication ADD CONSTRAINT FKDecisionsO608553
  FOREIGN KEY (fk_loan_application) REFERENCES LoanApplications (id)
  ON DELETE CASCADE;
